apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader-cluster
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list","watch"]
- apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
